config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resource :profile
  end
  
  resources :offers
  get '/galerie' => 'pages#galerie'
  get '/contact' => 'pages#contact'
  root 'offers#index'
 

end

app/models/offer.rb
class Offer < ActiveRecord::Base
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
    def index
        @offers = Offer.all
    end    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def galerie 
    end
    def contact
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
     @users = User.all
  end  
  
  def show
    @user = User.find( params[:id] )
  end
end  

app/helpers/application_helper.rb
module ApplicationHelper
    def cp(path)
        "current" if current_page?(path)
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cele mai bune oferte last minute din Grecia, Turcia, Egipt, Spania</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
		<meta charset="utf-8">
		<meta name="format-detection" content="telephone=no" />
		<meta name="description" content="Centralizam ofertele last minute ale agentiilor de top, si de incredere din Romania si ti le transmitem intr-un format usor de folosit" />
		<meta name="keywords" content="ammoudia,antalya,asprovalta,autocar,avion,barcelona,beach,brasov,brava,bucuresti,oferte,oferta,last,minute,last-minute,grecia,excursie,katerini,kefalonia,kusadasi,lastminute,lefkada,mallorca,oferte olympic,orase,parali,paralia-grecia,parga"/>

		<link rel="shortcut icon" type="image/png" href="/favicon.ico.png"/>
		<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-66095509-1', 'auto');
  ga('send', 'pageview');
		</script>
		<script>
/**
* Function that tracks a click on an outbound link in Google Analytics.
* This function takes a valid URL string as an argument, and uses that URL string
* as the event label.
*/
var trackOutboundLink = function(url) {
   ga('send', 'event', 'outbound', 'click', url, {'hitCallback':
     function () {
     document.location = url;
     }
   });
}
		</script>
		
		<script>
			$(document).ready(function(){
			jQuery('#camera_wrap').camera({
				loader: false,
				pagination: false ,
				minHeight: '444',
				thumbnails: false,
				height: '48.375%',
				caption: true,
				navigation: true,
				fx: 'simpleFade'
			});
			/*carousel*/
			var owl=$("#owl");
				owl.owlCarousel({
				items : 2, //10 items above 1000px browser width
				itemsDesktop : [995,2], //5 items between 1000px and 901px
				itemsDesktopSmall : [767, 2], // betweem 900px and 601px
				itemsTablet: [700, 2], //2 items between 600 and 0
				itemsMobile : [479, 1], // itemsMobile disabled - inherit from itemsTablet option
				navigation : true,
				pagination : false
				});
			$().UItoTop({ easingType: 'easeOutQuart' });
			});
		</script>
		<!--[if lt IE 8]>
		<div style=' clear: both; text-align:center; position: relative;'>
			<a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
				<img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
			</a>
		</div>
		<![endif]-->
		<!--[if lt IE 9]>
		<script src="js/html5shiv.js"></script>
		<link rel="stylesheet" media="screen" href="css/ie.css">
		<![endif]-->
</head>

<body class="page1" id="top">
<!--==============================header=================================-->
		<header>
			<div class="container_12">
				<div class="grid_12">
					<div class="menu_block">
						<nav class="horizontal-nav full-width horizontalNav-notprocessed">
							<ul class="sf-menu">
							  <li class= '<%= cp(root_path)%>'>
							  	<%= link_to 'TOP LASTMINUTE', root_path %>
							 </li>
							 
							  <li class= '<%= cp(galerie_path)%>'> 
							  <%= link_to 'GALERIE OFERTE', galerie_path, class: 'cp(galerie_path)' %>
							  </li>
							  
							  <li class= '<%= cp(contact_path)%>'> 
							  <%= link_to 'CONTACT', contact_path, class: 'cp(contact_path)'  %>
							  </li>
							</ul>
						</nav>
						<div class="clear"></div>
					</div>
				</div>
				<div class="grid_12">
					<h1>
						<a href="home.html">
							<img src="images/logo.png" alt="Top Lastminute">
						</a>
					</h1>
				</div>
			</div>
		</header>
<%= yield %>

<!--==============================footer=================================-->
		<footer>
			<div class="container_12">
				<div class="grid_12">
					<div class="socials">
						<a href="https://www.facebook.com/TopLastminute.ro" class="fa fa-facebook" target="_blank"></a>
					</div>
					<div class="copy">
						Top Lastminute &copy; <%= Time.now.year %>

					</div>
				</div>
			</div>
		</footer>


</body>
</html>

app/views/offers/index.html.erb

<!--==============================slider=================================-->	
		<div class="slider_wrapper">
			<div id="camera_wrap" class="">
				
			
				<% @offers.each do |offer| %>
				
					<% case %> 
						<% when offer.destination == "Peru" %>
							<div data-src="images/zakynthos.jpg" alt="zakynthos"> <!--user input image with paperclip-->
						<% when offer.destination == "Cluj" %>
							<div data-src="images/bodrum.jpg" alt="zakynthos">
						<% else %> 
							 <div data-src="images/corfu.jpg" alt="zakynthos">
					<% end %>
					
						<div class="caption fadeIn">
							<h2><%= offer.destination %></h2>
							<div class="price">
								<span><%= offer.price %></span>
							</div>
							<div class="extra_wrapper">
								<p><%= offer.description %></p>
							</div>
							<div class="extra_wrapper">
								<p><%= offer.transport %></p>
							</div>
							<div class="btn"><%= link_to 'VEZI OFERTA!', offer.link %></div>
						</div>		 	
					</div>
				<% end %>
			</div>
		</div>
		
<!--==============================Content=================================-->




app/views/pages/contact.html.erb

<!--==============================Content=================================-->
		<div class="content">
		  <div class="ic"></div>
			<div class="container_12">
				<div class="grid_5">
				  <p>&nbsp;</p>
				  <p>&nbsp;</p>
				  <p>&nbsp;</p>
				  <p>Vrei sa pleci in concediu?</p>
				  <p><br> 				    
				 Am  creat aceasta pagina in care gasesti cele mai bune <strong>oferte last minute. </strong></p>
				  <p><br> 				    
				  Centralizam <strong>ofertele last minute</strong> ale agentiilor  de top, si de incredere din Romania si ti le transmitem intr-un format usor de folosit, astfel incat in maxim 5 minute sa poti parcurge toate ofertele zilei, fara sa fie nevoie sa cauti pin site-urile ticsite cu informatii si cu anunturi care nu te  intereseaza.</p>
				  <p><br> 				    
				  In partea  de jos a paginii, gasesti un top 3 de <strong>oferte  last minute</strong>, din fiecare zi.</p>
				  <p><br> 				    
				  Urmareste-ne  si pe facebook. Actualizam zilnic pagina cu oferte irezistibile, raportate la pret, servicii incluse si destinatie. </p>
				  <p><br> 				    
				  Concediu  placut! </p>
				</div>
				<div class="grid_6 prefix_1">
					<div class="powr-contact-form" label="1635404"></div>
				</div>
			</div>
		</div>

app/views/pages/galerie.html.erb

<!--==============================Content=================================-->


app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3 text-center">
    <%= image_tag @user.profile.avatar.url, class: 'user-show-avatar' %>
  </div>
  <div class="col-md-6">
    <h1><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1>
    <h3><span class="job-title-icon"><%= job_title_icon %></span><%= @user.profile.job_title %></h3>
     <div class="well profile-description profile-block">
       <h3>Description</h3>
       <%= @user.profile.description %><br/>
     </div>
    <% if current_user.plan_id == 2 %>
    <div class="well profile-block contact-info">
      <h3>Contact Info</h3>
        <%= @user.profile.phone_number %><br/>
        <%= @user.profile.contact_email %><br/>
    </div>  
    <% end %>
   
  </div>
</div>